#!/usr/bin/env bash
# This script tells the story of /etc/passwd users using a while loop with IFS

while IFS=: read -r username password userid groupid fullname home shell; do
  echo "The user $username is part of the $groupid gang, lives in $home and rides $shell. $userid's place is protected by the passcode $password, more info about the user here: $userid"
done < /etc/passwd
